import { usePageMeta } from '../hooks/usePageMeta'

export default function TermsOfService() {
  usePageMeta({
    title: 'Terms of Service — MyFreePayStub',
    description: 'The terms governing use of MyFreePayStub\'s free pay stub generator, invoice generator, and tax calculators, including acceptable use, disclaimers, and limitation of liability.',
    canonicalPath: '/terms',
  })
  return (
    <div className="max-w-3xl mx-auto px-4 py-8">
      <h1 className="text-2xl font-black text-gray-800 mb-2">Terms of Service</h1>
      <p className="text-sm text-gray-400 mb-8">Last updated: June 27, 2026</p>

      <div className="space-y-8 text-sm text-gray-600">

        <section className="bg-red-50 border border-red-200 rounded-xl p-5">
          <h2 className="text-base font-bold text-red-800 mb-2">⚠️ Important — Read Before Using</h2>
          <ul className="space-y-2 text-red-700">
            <li>❌ This tool is <strong>NOT</strong> a licensed payroll service</li>
            <li>❌ Pay stubs generated here are <strong>NOT</strong> official payroll documents</li>
            <li>❌ <strong>Intentionally falsifying income information is illegal</strong> and may constitute fraud</li>
            <li>❌ We are <strong>NOT</strong> responsible for any decisions made based on this tool's output</li>
            <li>✅ This tool is for <strong>estimation and record-keeping purposes only</strong></li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-800 mb-3">1. Acceptance of Terms</h2>
          <p className="leading-relaxed">
            By accessing or using this website and any of its tools, calculators, or document
            generators — including the pay stub generator, paycheck calculator, hourly-to-salary
            calculator, overtime calculator, bonus tax calculator, self-employment / 1099 tax
            calculator, multiple pay stub generator, invoice generator, employment verification
            letter generator, and income verification packet builder (collectively, "the Tool") —
            you agree to be bound by these Terms of Service ("Terms").
            If you do not agree to these Terms, you must not use the Tool. These Terms apply to all
            visitors and users of the website.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-800 mb-3">2. Nature of the Tool — Not a Payroll Service</h2>
          <p className="leading-relaxed mb-3">
            MyFreePayStub is a free online tool that generates pay stub documents based on information
            provided by the user. It is provided for <strong>informational and general record-keeping
            purposes only</strong>. Specifically:
          </p>
          <ul className="space-y-2 ml-4 list-disc text-gray-600">
            <li>
              We are <strong>not a licensed payroll provider</strong>, employer of record, or
              professional employer organization (PEO).
            </li>
            <li>
              Pay stubs generated by this Tool are <strong>not official payroll documents</strong>
              and do not constitute proof of employment or official earnings verification from an employer.
            </li>
            <li>
              Tax calculations are <strong>estimates only</strong>, based on publicly available
              2026 IRS tax tables and approximate state tax rates. Actual tax withholding may differ
              based on your specific circumstances, exemptions, local taxes, and other factors.
            </li>
            <li>
              This Tool does <strong>not file payroll taxes</strong>, submit withholding to the IRS
              or any state agency, issue W-2 forms, or perform any official payroll function.
            </li>
            <li>
              Our calculators (including the self-employment / 1099 tax calculator and quarterly
              estimated tax estimates) provide <strong>simplified estimates for general planning only</strong>.
              They do not account for every credit, deduction, exemption, local tax, or individual
              circumstance, do not file or pay taxes on your behalf, and are <strong>not a substitute
              for the IRS Form 1040-ES worksheet or professional tax preparation</strong>.
            </li>
            <li>
              Documents such as invoices and employment verification letters are <strong>templates
              only</strong>. An employment verification letter is not valid unless it is completed and
              signed by an authorized representative of the actual employer. Issuing a verification
              letter, invoice, or pay stub that <strong>misrepresents employment, income, or job
              title</strong> — or signing one without authority to do so — may constitute fraud.
            </li>
            <li>
              The income verification packet builder only <strong>formats income figures you
              enter</strong> into a readable document. It does not confirm, audit, or guarantee the
              accuracy of that information, and is <strong>not issued or verified by any government
              agency, employer, or financial institution</strong>. It does not guarantee that any
              landlord, lender, or other third party will accept the resulting document. Data you
              enter is processed only in your browser for the current session — it is never sent to
              or stored on our servers, and is not saved to your device (no local storage); closing
              or refreshing the page clears it.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-800 mb-3">3. Prohibited Uses — Fraud Warning</h2>
          <div className="bg-red-50 border border-red-200 rounded-xl p-4 mb-3">
            <p className="text-red-800 font-bold text-sm">
              ⚠️ Using this Tool to create fraudulent income documentation is a serious crime.
            </p>
          </div>
          <p className="leading-relaxed mb-3">You agree that you will NOT use this Tool to:</p>
          <ul className="space-y-2 ml-4 list-disc text-gray-600">
            <li>
              <strong>Falsify income or employment information</strong> for any purpose, including
              but not limited to loan applications, mortgage applications, rental applications,
              visa applications, government benefit claims, or any other financial or legal purpose.
            </li>
            <li>
              Create documents that <strong>misrepresent your income, employer, employment status,
              or pay history</strong> to any lender, landlord, government agency, or third party.
            </li>
            <li>
              Engage in any form of <strong>identity theft, financial fraud, or document fraud</strong>.
            </li>
            <li>
              Use the output of this Tool as a <strong>substitute for officially issued payroll
              documents</strong> from a licensed payroll provider or employer.
            </li>
            <li>
              Violate any <strong>federal, state, or local laws</strong>, including laws relating
              to fraud, false statements, and misrepresentation.
            </li>
          </ul>
          <p className="leading-relaxed mt-3">
            Fraudulent use of pay stub documents may constitute federal wire fraud (18 U.S.C. § 1343),
            bank fraud (18 U.S.C. § 1344), or state-level offenses, potentially resulting in criminal
            prosecution, fines, and imprisonment. We reserve the right to report suspected fraudulent
            activity to relevant authorities.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-800 mb-3">4. User Responsibility and Accuracy</h2>
          <p className="leading-relaxed">
            You are <strong>solely responsible</strong> for:
          </p>
          <ul className="space-y-2 ml-4 list-disc text-gray-600 mt-2">
            <li>The accuracy and truthfulness of all information you enter into the Tool.</li>
            <li>
              Ensuring that any pay stub generated complies with applicable federal, state,
              and local laws and regulations in your jurisdiction.
            </li>
            <li>
              Verifying tax calculations with a qualified payroll professional or CPA before
              relying on them for any official purpose.
            </li>
            <li>
              Any consequences arising from the use of pay stubs generated by this Tool,
              including any legal or financial consequences.
            </li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-800 mb-3">5. Disclaimer of Warranties</h2>
          <p className="leading-relaxed">
            THE TOOL IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT ANY WARRANTIES OF ANY KIND,
            EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY,
            FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, OR NON-INFRINGEMENT.
          </p>
          <p className="leading-relaxed mt-3">
            We do not warrant that:
          </p>
          <ul className="space-y-2 ml-4 list-disc text-gray-600 mt-2">
            <li>Tax calculations are accurate, complete, or current.</li>
            <li>The Tool will meet your specific requirements.</li>
            <li>The Tool will be error-free or uninterrupted.</li>
            <li>Pay stubs generated will be accepted by any lender, landlord, or government agency.</li>
          </ul>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-800 mb-3">6. Limitation of Liability</h2>
          <p className="leading-relaxed">
            TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, WE SHALL NOT BE LIABLE FOR ANY
            INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, INCLUDING BUT NOT
            LIMITED TO LOSS OF INCOME, LOSS OF DATA, FINANCIAL LOSS, OR ANY OTHER DAMAGES ARISING
            FROM YOUR USE OF OR INABILITY TO USE THE TOOL, EVEN IF WE HAVE BEEN ADVISED OF THE
            POSSIBILITY OF SUCH DAMAGES.
          </p>
          <p className="leading-relaxed mt-3">
            Our total liability to you for any claim arising out of or relating to these Terms
            or the Tool shall not exceed zero dollars ($0.00), as the Tool is provided free of charge.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-800 mb-3">7. Tax and Legal Disclaimer</h2>
          <p className="leading-relaxed">
            Nothing on this website constitutes tax advice, legal advice, payroll advice, or
            financial advice. Tax laws are complex and subject to change. State tax rates and
            rules vary significantly and may not be fully reflected in our estimates. Always
            consult a <strong>qualified CPA, tax professional, or licensed payroll provider</strong>
            for official payroll processing, tax filing, and compliance.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-800 mb-3">8. Intellectual Property</h2>
          <p className="leading-relaxed">
            The design, code, and content of this website are owned by MyFreePayStub and protected
            by applicable intellectual property laws. You may use the Tool for personal or
            business purposes in accordance with these Terms, but you may not copy, reproduce,
            or redistribute the website's code or content without our permission.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-800 mb-3">9. Modifications</h2>
          <p className="leading-relaxed">
            We reserve the right to modify these Terms at any time. Changes will be posted on
            this page with an updated date. Your continued use of the Tool after changes are
            posted constitutes your acceptance of the updated Terms.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-800 mb-3">10. Governing Law</h2>
          <p className="leading-relaxed">
            These Terms shall be governed by and construed in accordance with applicable law.
            Any disputes arising under these Terms shall be resolved in the appropriate courts
            of competent jurisdiction.
          </p>
        </section>

        <section>
          <h2 className="text-base font-bold text-gray-800 mb-3">11. Contact</h2>
          <p className="leading-relaxed">
            For questions about these Terms, contact us at{' '}
            <a href="mailto:hello@myfreepaystub.com" className="text-blue-500 hover:underline">
              hello@myfreepaystub.com
            </a>.
          </p>
        </section>

      </div>
    </div>
  )
}